#!/usr/bin/env node
// UndoKit dependency license audit (QA-owned).
//
//   node scripts/license-audit.mjs           regenerate docs/DEPENDENCY-LICENSES.md
//   node scripts/license-audit.mjs --check   fail (exit 1) if the file is stale or a runtime license needs review
//
// Reads package-lock.json for the dependency set and node_modules/<pkg>/package.json for each license.
// No network access. Output is deterministic (no timestamps) so --check is a byte comparison.

import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outFile = join(root, "docs", "DEPENDENCY-LICENSES.md");
const check = process.argv.includes("--check");

const PERMISSIVE = new Set([
  "MIT",
  "MIT-0",
  "ISC",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Apache-2.0",
  "0BSD",
  "BlueOak-1.0.0",
  "CC0-1.0",
  "Unlicense",
  "Python-2.0",
  "PostgreSQL",
  "Zlib",
]);
// Allowed only for build/test tooling that is not shipped in the runtime package.
const DEV_ONLY_OK = new Set(["MPL-2.0", "CC-BY-4.0", "CC-BY-3.0", "LGPL-3.0-or-later"]);

function normalizeLicense(pkg) {
  const l = pkg.license ?? pkg.licenses;
  if (typeof l === "string") return l.trim();
  if (l && typeof l === "object" && !Array.isArray(l) && typeof l.type === "string") return l.type.trim();
  if (Array.isArray(l)) return l.map((x) => (typeof x === "string" ? x : x?.type)).filter(Boolean).join(" OR ");
  return "UNKNOWN";
}

// Evaluate a simple SPDX expression against an allow-set. OR needs one allowed term, AND needs all.
function satisfies(expr, allowed) {
  const cleaned = expr.replace(/[()]/g, " ").trim();
  if (!cleaned) return false;
  const orGroups = cleaned.split(/\s+OR\s+/i);
  return orGroups.some((group) =>
    group
      .split(/\s+AND\s+/i)
      .map((t) => t.trim().replace(/\+$/, ""))
      .every((t) => allowed.has(t)),
  );
}

function classify(license, isDev) {
  if (satisfies(license, PERMISSIVE)) return "ok";
  if (isDev && satisfies(license, new Set([...PERMISSIVE, ...DEV_ONLY_OK]))) return "ok-dev-only";
  return "REVIEW";
}

const lockPath = join(root, "package-lock.json");
if (!existsSync(lockPath)) {
  console.error("license-audit: package-lock.json not found");
  process.exit(2);
}
const lockRaw = readFileSync(lockPath, "utf8");
const lock = JSON.parse(lockRaw);
const lockHash = createHash("sha256").update(lockRaw).digest("hex");
const rootPkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

const rows = [];
const notInstalled = [];
for (const [key, meta] of Object.entries(lock.packages ?? {})) {
  if (key === "") continue;
  const name = key.replace(/^.*node_modules\//, "");
  const dir = join(root, key);
  const pj = join(dir, "package.json");
  const isDev = meta.dev === true;
  if (!existsSync(pj)) {
    notInstalled.push({ name, version: meta.version ?? "?", optional: meta.optional === true, lockLicense: meta.license ?? null });
    continue;
  }
  const pkg = JSON.parse(readFileSync(pj, "utf8"));
  const license = normalizeLicense(pkg);
  rows.push({
    name: pkg.name ?? name,
    version: pkg.version ?? meta.version ?? "?",
    license,
    scope: isDev ? "dev" : "runtime",
    status: classify(license, isDev),
  });
}
rows.sort((a, b) => (a.scope === b.scope ? a.name.localeCompare(b.name) : a.scope === "runtime" ? -1 : 1));
notInstalled.sort((a, b) => a.name.localeCompare(b.name));

const review = rows.filter((r) => r.status === "REVIEW");
const runtimeReview = review.filter((r) => r.scope === "runtime");
const counts = new Map();
for (const r of rows) counts.set(r.license, (counts.get(r.license) ?? 0) + 1);

const lines = [];
lines.push("# Dependency license audit");
lines.push("");
lines.push("Generated by `node scripts/license-audit.mjs`. Do not edit by hand. Regenerate after any dependency change.");
lines.push("");
lines.push(`- Project: ${rootPkg.name}@${rootPkg.version} (${rootPkg.license ?? "no license field"})`);
lines.push(`- Lockfile sha256: \`${lockHash}\``);
lines.push(`- Installed packages audited: ${rows.length} (${rows.filter((r) => r.scope === "runtime").length} runtime, ${rows.filter((r) => r.scope === "dev").length} dev)`);
lines.push(`- Lockfile entries not installed on the audit machine (platform-specific optional packages): ${notInstalled.length}`);
lines.push(`- Needs review: ${review.length} (${runtimeReview.length} runtime)`);
lines.push("");
lines.push("Policy: runtime dependencies must be permissive (MIT, ISC, BSD, Apache-2.0 and similar). Weak-copyleft or attribution licenses are accepted for dev-only tooling that is not shipped. A runtime package outside the policy fails `--check`.");
lines.push("");
lines.push("## License summary");
lines.push("");
lines.push("| License | Packages |");
lines.push("| --- | --- |");
for (const [lic, n] of [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))) {
  lines.push(`| ${lic} | ${n} |`);
}
lines.push("");
lines.push("## Packages needing review");
lines.push("");
if (review.length === 0) lines.push("None.");
else {
  lines.push("| Package | Version | License | Scope |");
  lines.push("| --- | --- | --- | --- |");
  for (const r of review) lines.push(`| ${r.name} | ${r.version} | ${r.license} | ${r.scope} |`);
}
lines.push("");
lines.push("## All installed packages");
lines.push("");
lines.push("| Package | Version | License | Scope | Status |");
lines.push("| --- | --- | --- | --- | --- |");
for (const r of rows) lines.push(`| ${r.name} | ${r.version} | ${r.license} | ${r.scope} | ${r.status} |`);
lines.push("");
lines.push("## Lockfile entries not installed here");
lines.push("");
lines.push("These are optional, platform-specific binaries. They are NOT audited on this machine; their licenses are recorded only when the lockfile carries them.");
lines.push("");
if (notInstalled.length === 0) lines.push("None.");
else {
  lines.push("| Package | Version | Optional | License in lockfile |");
  lines.push("| --- | --- | --- | --- |");
  for (const n of notInstalled) lines.push(`| ${n.name} | ${n.version} | ${n.optional ? "yes" : "no"} | ${n.lockLicense ?? "not recorded"} |`);
}
lines.push("");
const content = lines.join("\n");

if (check) {
  const current = existsSync(outFile) ? readFileSync(outFile, "utf8") : "";
  if (current !== content) {
    console.error("license-audit: docs/DEPENDENCY-LICENSES.md is stale. Run: node scripts/license-audit.mjs");
    process.exit(1);
  }
  if (runtimeReview.length > 0) {
    console.error(`license-audit: ${runtimeReview.length} runtime package(s) need license review`);
    process.exit(1);
  }
  console.log(`license-audit: up to date, ${rows.length} packages, ${review.length} needing review (0 runtime)`);
} else {
  writeFileSync(outFile, content);
  console.log(`license-audit: wrote docs/DEPENDENCY-LICENSES.md (${rows.length} packages, ${review.length} needing review)`);
  if (runtimeReview.length > 0) process.exit(1);
}
